### 添加设备
POST http://127.0.0.1:12100/station/api/device
Content-Type: application/json

{
    "deviceNo": "20198002",
    "deviceName": "",
    "icon": "",
    "chlCount": 4,
    "chlNames": "CH01,CH02,CH03,CH04",
    "ioCount": 1,
    "ioNames": "IO01"
}

### 批量添加设备
POST http://127.0.0.1:12100/station/api/device/batchAdd
Content-Type: application/json

{
    "organizeGuid": "NOgJHGFHmVh1KJdUgYIedd",
    "prefix": "2019",
    "count": 100,
    "startNumber": 8003,
    "chlCount": 4,
    "chlNames": "CH01,CH02,CH03,CH04",
    "ioCount": 1,
    "ioNames": "IO01",
    "icon": ""
}

### 设备列表
GET http://127.0.0.1:12100/station/api/device/list
Content-Type: application/json

{

}

### 设备信息
GET http://127.0.0.1:12100/station/api/device/1
Content-Type: application/json

{

}


### 更新设备信息
PUT http://127.0.0.1:12100/station/api/device
Content-Type: application/json

{
    "deviceId": 1,
    "deviceName": "测试001",
    "icon": ""
}


### 删除设备信息
DELETE  http://127.0.0.1:12100/station/api/device/3
Content-Type: application/json

{

}



### 获取设备状态数据
GET http://127.0.0.1:12100/station/api/device/status/list?deviceNo=20198002&startTime=2021-12-09 00:00:00&endTime=2021-12-09 23:59:59&desc=dtu
Content-Type: application/json

{

}

### 获取设备状态数据
GET http://127.0.0.1:12100/station/api/device/status/list?deviceNo=20198002&startTime=2021-12-09 00:00:00&endTime=2021-12-09 23:59:59&flag=2&desc=dtu
Content-Type: application/json

{

}


### 获取设备上下线数据
GET http://127.0.0.1:12100/station/api/device/online/list?deviceNo=20198002&startTime=2021-12-09 00:00:00&endTime=2021-12-09 23:59:59
Content-Type: application/json

{

}

### 获取设备报警数据
GET http://127.0.0.1:12100/station/api/device/alarm/list?deviceNo=20198002&startTime=2021-12-09 00:00:00&endTime=2021-12-09 23:59:59
Content-Type: application/json

{

}


### 获取设备报警数据
GET http://127.0.0.1:12100/station/api/device/alarm/link/list?deviceNo=800888&startTime=2021-12-09 00:00:00&endTime=2021-12-13 23:59:59&guid=1639159344002007000000800888
Content-Type: application/json

{

}

### 获取指定状态id报警
GET http://127.0.0.1:12100/station/api/device/alarm/bystatus/427788605789827072
Content-Type: application/json

{

}

### 获取设备指定id状态数据
GET http://127.0.0.1:12100/station/api/device/status?deviceId=1&statusId=409377188543983616
Content-Type: application/json

{

}
