### 录像查询
POST http://127.0.0.1:12100/station/api/device/request/query?deviceNo=20198002
Content-Type: application/json

{
    "startTime": "2021-12-15 00:00:00",
    "endTime": "2021-12-15 23:59:59",
    "channelList": "1",
    "fileType": 1
}

### 实时流请求
// streamType 0 子码流 1 主码流
POST http://127.0.0.1:12100/station/api/device/request/liveStream?deviceNo=20198002
Content-Type: application/json

{
    "server": "172.16.50.219:33000",
    "session": "live_20198002_01_00",
    "channel": 1,
    "streamType": 0,
    "on": 1
}


### 远程回放
// fileName 设备文件名
POST http://127.0.0.1:12100/station/api/device/request/playback?deviceNo=20198002
Content-Type: application/json

{
    "server": "172.16.50.219:33000",
    "name": "/0000_00fb0000_6_1620604800_1620605069_0_127644266.avi"
}


### 远程回放
// 按时间段回放
POST http://127.0.0.1:12100/station/api/device/request/playback?deviceNo=20198002
Content-Type: application/json

{
    "server": "172.16.50.219:22000",
    "startTime": "2022-03-07 09:00:00",
    "endTime": "2022-03-07 09:02:00",
    "channels": "2"
}


### 设备控制

POST http://127.0.0.1:12100/station/api/device/request/control?deviceNo=20198002
Content-Type: application/json

{

}

### ftp文件传输

POST http://127.0.0.1:12100/station/api/device/request/ftpTransfer?deviceNo=20198002
Content-Type: application/json

{
    "ftpUrl": "ftp://don:123456@172.16.50.219:21",
    "fileSrc": "/mnt/sd2/picture/Pic20210518153224157A02.jpg",
    "fileDst": "20198002.Pic20210518153224157A02.jpg",
    "action": 0,
    "fileType": 4
}

### file文件传输

POST http://127.0.0.1:12100/station/api/device/request/fileTransfer?deviceNo=20198002
Content-Type: application/json

{
    "fileName": "/mnt/sd2/capture/20210831/1630430088212CH02T2.jpg",
    "fileType": 3,
    "action": 0,
    "server": "172.16.50.219:22000",
    "offset": 0
}


### file文件传输

POST http://127.0.0.1:12100/station/api/device/request/fileTransfer?deviceNo=20198002
Content-Type: application/json

{
    "fileName": "Z:\\mdvr_protocol\\LINUX\\tag\\howen_20190916\\app_hw3520\\release\\HW3520D-V16072701-V220304T0.491.sw",
    "fileType": 5,
    "action": 1,
    "server": "172.16.50.219:22000",
    "offset": 0
}

### 串口透传设置, 应答的session用于透传数据, 设置为"", 系统会自动生成并返回。

POST http://127.0.0.1:12100/station/api/device/request/transparent?deviceNo=20198002
Content-Type: application/json

{
    "session": "20ffc9c7-9c67-4c1f-8f93-5dcd15ba2395",
    "port": 1,
    "baudRate": 15200,
    "dataBit": 8,
    "checkBit": 0,
    "stopBit": 1
}

### 透传数据
# type:1 字符串 如 abcdefg
# type:2 Hex   031F269D

POST http://127.0.0.1:12100/station/api/device/request/transfer?deviceNo=20198002&session=ca03fffb-0310-4cc1-8191-e4aae455b7f8
Content-Type: application/json

{
    "type": 2,
    "data": "031F269D"
}


### 关闭链接, session存在关闭媒体链路。不存在关闭信令链路

POST http://127.0.0.1:12100/station/api/device/request/close?deviceNo=20198002&session=ca03fffb-0310-4cc1-8191-e4aae455b7f8
Content-Type: application/json

{
   
}