### 配置公网ip，此ip需要下发给设备
host: "172.16.50.219"
license: "localstation.lice"
public: "public"

### 端口
port: 
 http: 12100
 access: 22000

# Ftp服务
ftp:
  enable: true
  address: "ftp://admin:123456@127.0.0.1:2211"

### 地图
map: 
 name: "Baidu"
 key: ""

sql: ### SQL
 name: "mysql"
 address: "root:123456@tcp(172.16.50.219:3306)/station?charset=utf8&parseTime=True&loc=Local"
# address="xstation.db"
# address="user=postgres password=123456 dbname=xstation port=5432 sslmode=disable TimeZone=Asia/Shanghai"
