### 配置公网ip，此ip需要下发给设备
Host= "172.16.50.219"
License= "localstation.lice"
Public= "public"

### 端口
[Port]
  Http= 12100
  Access= 22000

# Ftp服务
[Ftp]
    Enable= true
    User= "admin"
    Pswd= "123456"
    Port= 2211
    
### SQL
[Sql] 
  Name= "mysql"
  Address= "root:123456@tcp(127.0.0.1:3306)/station?charset=utf8&parseTime=True&loc=Local"

### 地图
[Map] 
  Name= "Baidu"
  Key= ""