http: ### Serve, 如不在同一台服务器，请配置公网ip
 host: "127.0.0.1"
 port: 12100

access: ### 配置公网ip，此ip需要下发给设备
 host: "172.16.50.219"
 port: 22000

sql: ### SQL
 name: "mysql"
 address: "root:123456@tcp(172.16.50.219:3306)/station?charset=utf8&parseTime=True&loc=Local"
# Address="xstation.db"
# Address="user=postgres password=123456 dbname=xstation port=5432 sslmode=disable TimeZone=Asia/Shanghai"
map: ### 地图
 name: "Baidu"
 key: ""

ftp:
  user: "admin"
  pswd: "123456"
  port: "2211"

license: "localstation.lice"