### 配置公网ip，此ip需要下发给设备
host: "172.16.50.219"
license: "localstation.lice"
public: "public"
### 端口
port:
  http: 12100
  access: 22000

# Ftp服务
ftp:
  enable: true
  option:
    port: 2211
    user: "admin"
    pswd: "123456"

### SQL
sql:
  name: "mysql"
  address: "root:123456@tcp(127.0.0.1:3306)/station?charset=utf8&parseTime=True&loc=Local"

superior:
  api: "http://localhost:8080/xserver"

### 第三方Hook
hook:
  enable: true
  options:
    - name: "nats"
      address: "nats://127.0.0.1:4222"
      status: "device.status"
      online: "device.online"
      alarm: "device.alarm"
      event: "device.event"
    # - name: "http://"
    #   address: "localhost:8080/xserver"
    #   online: "notify/devonline"
    #   status: "notifydevstatus"
    #   alarm: "notifydevalarm"
    #   event: "notify/devevent"
