### Serve Port
[Port]
Http=12100
Rpc=12110
Access=33000

### SQL
[SQL]
Name="mysql"
Address="root:123456@tcp(127.0.0.1:3306)/xstation?charset=utf8&parseTime=True&loc=Local" # Name="mysql"
# Address="xstation.db"
# Address="user=postgres password=123456 dbname=xstation port=5432 sslmode=disable TimeZone=Asia/Shanghai"

[Map]
Name="Baidu"
Key="MkStYYmSDxUSZCrb4SzWESsSHVkMURD8"