host: "172.16.50.219" ### 配置公网ip，此ip需要下发给设备
license: "localstation.lice"
guid: "gQSmPuboIGQahHdxQisOOk"
public: "public"
super: ### 中心服务
  api: ""
port: ### 端口
  http: 12100
  access: 20000
ftp: # Ftp服务
  enable: true
  port: 2211
  user: "admin"
  pswd: "123456"
sql: ### SQL
  name: "mysql"
  address: "root:123456@tcp(127.0.0.1:3306)/station?charset=utf8&parseTime=True&loc=Local"
hooks: ### 第三方Hook
  - address: "nats://127.0.0.1:4222"
    online: "device.online"
    status: "device.status"
    alarm: "device.alarm"
    event: "device.event"
# - address: "http://localhost:8080/xserver/notify"
#     online: "devonline"
#     status: "devstatus"
#     alarm: "devalarm"
#     event: "devevent"
