@baseUrl=172.16.50.219:12100/xstation/api/device
@access=172.16.50.219:33000
@deviceId=20198002

### 录像查询
POST http://{{baseUrl}}/request/query
?deviceId={{deviceId}}
Content-Type: application/json

{
    "startTime": "2021-06-10 00:00:00",
    "endTime": "2021-06-10 23:59:59",
    "channelList": "1",
    "fileType": 1
}

### 实时流请求
// streamType 0 子码流 1 主码流
POST http://{{baseUrl}}/request/liveStream
?deviceId={{deviceId}}
Content-Type: application/json

{
    "server": "{{access}}",
    "session": "live_{{deviceId}}_01_00",
    "channel": 1,
    "streamType": 0,
    "on": 1
}


### 远程回放
// fileName 设备文件名
POST http://{{baseUrl}}/request/playback
?deviceId={{deviceId}}
Content-Type: application/json

{
    "server": "{{access}}",
    "name": "T/0000_039f0000_6_1621900800_1621900817_0_8034540.avi"
}


### 远程回放
// 按时间段回放
POST http://{{baseUrl}}/request/playback
?deviceId={{deviceId}}
Content-Type: application/json

{
    "server": "{{access}}",
    "startTime": "2021-01-06 10:00:00",
    "endTime": "2021-01-06 10:05:00",
    "channels": "1;2"
}


### 参数设置

POST http://{{baseUrl}}/request/parameters
?deviceId={{deviceId}}
Content-Type: application/json

{
    "RSBASE": {
      "rs0": {
        "baudrate": "115200",
        "databit": "8",
        "func": "15",
        "parity": "2",
        "stopbit": "1"
      },
      "rs1": {
        "baudrate": "9600",
        "databit": "8",
        "func": "0",
        "parity": "2",
        "stopbit": "1"
      },
      "rs2": {
        "baudrate": "2400",
        "databit": "8",
        "func": "2",
        "parity": "2",
        "stopbit": "1"
      },
      "rs3": {
        "baudrate": "115200",
        "databit": "5",
        "func": "0",
        "parity": "3",
        "stopbit": "1"
      },
      "rs4": {
        "baudrate": "9600",
        "databit": "8",
        "func": "1",
        "parity": "1",
        "stopbit": "0"
      },
      "rs5": {
        "baudrate": "11520",
        "databit": "8",
        "func": "1",
        "parity": "2",
        "stopbit": "1"
      },
      "rs6": {
        "baudrate": "11520",
        "databit": "8",
        "func": "1",
        "parity": "0",
        "stopbit": "1"
      },
      "rs7": {
        "baudrate": "11520",
        "databit": "8",
        "func": "1",
        "parity": "0",
        "stopbit": "1"
      }
    }
}

### 参数获取

POST http://{{baseUrl}}/request/parameters
?deviceId={{deviceId}}
Content-Type: application/json

{
    "JTBASE":""
}

### UserDefineHowen 参数获取
// act: 1
POST http://{{baseUrl}}/request/parameters
?deviceId={{deviceId}}
Content-Type: application/json

{
    "UserDefineHowen": {
        "act": 1,
        "type": 253
    }
}

### UserDefineHowen 参数设置
// act: 0

POST http://{{baseUrl}}/request/parameters
?deviceId={{deviceId}}
Content-Type: application/json

{
    "UserDefineHowen": {
        "act": 0,
        "type": 300,
        "data": {
          "channels": 3,
          "interval": 60,
          "res": 0
        }
    }
}

### GpsAngle 参数获取
// act: 1
POST http://{{baseUrl}}/request/parameters
?deviceId={{deviceId}}
Content-Type: application/json

{
    "gpsAngleConfig": {
        "act": 0,
        "dg": 3000,
        "on": 0
    }
}

### GpsAngle 参数设置
// act: 1
POST http://{{baseUrl}}/request/parameters
?deviceId={{deviceId}}
Content-Type: application/json

{
    "gpsAngleConfig": {
        "act": 1
    }
}

### 设备控制

POST http://{{baseUrl}}/request/control
?deviceId={{deviceId}}
Content-Type: application/json

{

}

### ftp文件传输

POST http://{{baseUrl}}/request/ftpTransfer
?deviceId={{deviceId}}
Content-Type: application/json

{
    "ftpUrl": "ftp://don:123456@172.16.50.219:21",
    "fileSrc": "HW3521V2-V18092801-V210513T0.105.sw",
    "fileDst": "",
    "action": 1,
    "fileType": 5
}

### file文件传输

POST http://{{baseUrl}}/request/fileTransfer
?deviceId={{deviceId}}
Content-Type: application/json

{
    "fileName": "/mnt/sd2/debug/dbglog-20210525-153908.log",
    "fileType": 7,
    "action": 0,
    "server": "{{access}}",
    "fileSize": 0,
    "offset": 0
}

### 串口透传设置, 应答的session用于透传数据, 设置为"", 系统会自动生成并返回。

POST http://{{baseUrl}}/request/serial/transparent
?deviceId={{deviceId}}
Content-Type: application/json

{
    "session": "20ffc9c7-9c67-4c1f-8f93-5dcd15ba2395",
    "port": 1,
    "baudRate": 15200,
    "dataBit": 8,
    "checkBit": 0,
    "stopBit": 1
}

### 透传数据
# type:1 字符串 如 abcdefg
# type:2 Hex   031F269D

POST http://{{baseUrl}}/request/serial/transfer
?deviceId={{deviceId}}
&session=ca03fffb-0310-4cc1-8191-e4aae455b7f8
Content-Type: application/json

{
    "type": 2,
    "data": "031F269D"
}


### 关闭链接, session存在关闭媒体链路。不存在关闭信令链路

POST http://{{baseUrl}}/request/close
?deviceId={{deviceId}}
&session=live_{{deviceId}}_01_00
Content-Type: application/json

{
   
}

@upgrade=UpgradeFile
### 文件上传
POST http://{{baseUrl}}/xstation/api/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="{{upgrade}}";
Content-Type: text/plain

< Z:\\{{upgrade}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### file文件传输

POST http://{{baseUrl}}/request/fileTransfer
?deviceId={{deviceId}}
Content-Type: application/json

{
    "fileName": "{{upgrade}}",
    "fileType": 5,
    "action": 1,
    "server": "{{access}}",
    "fileSize": 13022129,
    "offset": 0
}