
### ptz ptz
### code 参考协议文档

POST http://127.0.0.1:12100/xstation/api/device/control/ptz?deviceId=20198002
Content-Type: application/json

{
    "code": 24,
    "channel": 8,
    "speed": 4
}

### 重启

POST http://127.0.0.1:12100/xstation/api/device/control/reboot?deviceId=20198002
Content-Type: application/json

{

}

### 抓拍

POST http://127.0.0.1:12100/xstation/api/device/control/capture?deviceId=20198002
Content-Type: application/json

{
    "channelList": "1;2",
    "reslution": 4
}

### 设备控制

POST http://127.0.0.1:12100/xstation/api/device/control/osd?deviceId=20198002
Content-Type: application/json

{
    "osdSpeed": "obd"
}


### 格式化磁盘

POST http://127.0.0.1:12100/xstation/api/device/control/format?deviceId=20198002
Content-Type: application/json

{
    "name": "sd1"
}


### GSensor校准

POST http://127.0.0.1:12100/xstation/api/device/control/gsensor?deviceId=20198002
Content-Type: application/json

{

}

### 恢复出厂设置

POST http://127.0.0.1:12100/xstation/api/device/control/reset?deviceId=20198002
Content-Type: application/json

{

}

### 车辆控制
// code 参考文档act
POST http://127.0.0.1:12100/xstation/api/device/control/vehicle?deviceId=20198002
Content-Type: application/json

{
    "code": 1
}