### 服务授权

POST http://127.0.0.1:12100/station/serve/applyAuth
Content-Type: application/json

{
    "identity": "EoxNZSJjfJxpxwj7q9SWED",
    "username": "admin",
    "password": "admin"
}


### 获取已添加服务列表

GET http://127.0.0.1:12100/station/api/serve/list
Content-Type: application/json

{

}



### 获取已添加服务状态

GET http://127.0.0.1:12100/station/api/serve/status/list
Content-Type: application/json

{

}


### 添加新服务

POST http://127.0.0.1:12100/station/api/serve
Content-Type: application/json

{
    "name": "stroge",
    "httpPort": 12300,
    "rpcPort": 12310,
    "accessPort": 12320,
    "status": 1,
    "role": 3
}

### 获取服务

GET http://127.0.0.1:12100/station/api/serve/get/lbDFjWpEtTVgcpzRgmAPQh
Content-Type: application/json

{

}


### 修改服务状态

PUT http://127.0.0.1:12100/station/api/serve/status
Content-Type: application/json

{
    "guid": "92Wub04vsFyOmWISSnwl6T",
    "status": 1
}

### 获取服务

DELETE  http://127.0.0.1:12100/station/api/serve
Content-Type: application/json

{
    "guid": [
        "lbDFjWpEtTVgcpzRgmAPQh",
        ""
    ]
}